[package]
name = "sail2mars"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "3.0.7", features = ["derive"] }
sailar = { git = "https://github.com/davnavr/SAILAR-lang" }
sailar_get = { git = "https://github.com/davnavr/SAILAR-lang" }
thiserror = "1.0.30"
